# Generated by Django 3.0.1 on 2021-01-02 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0002_auto_20210102_0740'),
    ]

    operations = [
        migrations.AddField(
            model_name='spotifytoken',
            name='access_token',
            field=models.CharField(default='', max_length=150),
            preserve_default=False,
        ),
    ]
